file(READ "${PROJECT_ROOT}/src/Features/VR.cpp" _source)
string(FIND "${_source}" "struct VRFpsStabilizerUIState" _start)
string(FIND "${_source}" "bool DrawVRFpsStabilizerUpscaleMethod(" _end)
if(_start EQUAL -1 OR _end LESS_EQUAL _start)
    message(FATAL_ERROR "Cannot extract the Stabilizer profile editor")
endif()
math(EXPR _length "${_end} - ${_start}")
string(SUBSTRING "${_source}" ${_start} ${_length} _implementation)
file(WRITE "${OUTPUT_FILE}" "${_implementation}")

file(READ "${PROJECT_ROOT}/src/Features/Upscaling.cpp" _source)
string(FIND "${_source}" "constexpr std::array<uint32_t, Upscaling::kQualityModeMaxIndex + 1> kVRFpsStabilizerUpscalePresets" _start)
string(FIND "${_source}" "enum class VRFpsStabilizerSetting" _end)
if(_start EQUAL -1 OR _end LESS_EQUAL _start)
    message(FATAL_ERROR "Cannot extract the Stabilizer preset mapping")
endif()
math(EXPR _length "${_end} - ${_start}")
string(SUBSTRING "${_source}" ${_start} ${_length} _implementation)
file(APPEND "${OUTPUT_FILE}" "\n${_implementation}")

string(FIND "${_source}" "uint32_t VRFpsStabilizerQualityModeToUpscalePreset(" _start)
string(FIND "${_source}" "const char* GetVRFpsStabilizerSettingName(" _end)
if(_start EQUAL -1 OR _end LESS_EQUAL _start)
    message(FATAL_ERROR "Cannot extract the Stabilizer preset writer")
endif()
math(EXPR _length "${_end} - ${_start}")
string(SUBSTRING "${_source}" ${_start} ${_length} _implementation)
file(APPEND "${OUTPUT_FILE}" "\n${_implementation}")
