if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()

file(READ "${PROJECT_ROOT}/src/Features/ScreenshotApi.cpp" _source)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")

function(extract_dispatch_region start end output)
    string(FIND "${_source}" "${start}" _start)
    if(_start EQUAL -1)
        message(FATAL_ERROR "Screenshot dispatch test cannot find ${start}")
    endif()
    string(SUBSTRING "${_source}" ${_start} -1 _remaining)
    string(FIND "${_remaining}" "${end}" _end)
    if(_end EQUAL -1)
        message(FATAL_ERROR "Screenshot dispatch test cannot find ${end}")
    endif()
    string(SUBSTRING "${_remaining}" 0 ${_end} _extracted)
    set(${output} "${_extracted}" PARENT_SCOPE)
endfunction()

extract_dispatch_region("void ScreenshotApi::MarkSequenceCancellationLocked(" "void ScreenshotApi::Tick(" _queue_cancellation)
extract_dispatch_region("void ScreenshotApi::OnFeatureDisabled(" "bool ScreenshotApi::DrainForShutdown(" _lifecycle)
file(WRITE "${OUTPUT_DIRECTORY}/screenshot_dispatch_under_test.h" "${_queue_cancellation}\n${_lifecycle}")
