if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()
file(READ "${PROJECT_ROOT}/src/Features/LightLimitFix.cpp" _source)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
set(_output "")
function(extract_between start end)
    string(FIND "${_source}" "${start}" _start)
    if(_start EQUAL -1)
        message(FATAL_ERROR "Scene guard integration cannot find ${start}")
    endif()
    string(SUBSTRING "${_source}" ${_start} -1 _remaining)
    string(FIND "${_remaining}" "${end}" _end)
    if(_end EQUAL -1)
        message(FATAL_ERROR "Scene guard integration cannot find ${end}")
    endif()
    string(SUBSTRING "${_remaining}" 0 ${_end} _extracted)
    set(_output "${_output}\n${_extracted}" PARENT_SCOPE)
endfunction()
extract_between("constexpr int kVRNiAVObjectFlagsOffset" "struct VRCullingProcessVtableSpec")
extract_between("bool IsReadableRange(const void* a_ptr, std::size_t a_size) noexcept;" "class VREffectShaderFirstLightGuard")
extract_between("class VRSceneGraphCullingObjectGuard" "enum class VRRoomLightCullingUse")
extract_between("bool IsReadableRange(const void* a_ptr, std::size_t a_size) noexcept\n\t{" "bool IsSafeLightRange")
extract_between("bool IsExecutableAddress" "bool IsSafeDirectionalNiLight")
extract_between("void LightLimitFix::Hooks::InstallVRSceneGraphCullingObjectGuard()" "void LightLimitFix::Hooks::InstallVRRoomLightCullingProcessGuards()")
string(
    REPLACE "return GetModuleHandleW(L\"EngineFixes.dll\") != nullptr;"
            "return engineFixesLoaded;"
            _output
            "${_output}"
)
file(WRITE "${OUTPUT_DIRECTORY}/vr_scene_guards_under_test.h" "${_output}")
