if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
set(_output "")
function(extract_between path start end)
    file(READ "${PROJECT_ROOT}/${path}" _source)
    string(FIND "${_source}" "${start}" _start)
    if(_start EQUAL -1)
        message(FATAL_ERROR "Scene depth integration cannot find ${start}")
    endif()
    string(SUBSTRING "${_source}" ${_start} -1 _remaining)
    string(FIND "${_remaining}" "${end}" _end)
    if(_end EQUAL -1)
        message(FATAL_ERROR "Scene depth integration cannot find ${end}")
    endif()
    string(SUBSTRING "${_remaining}" 0 ${_end} _extracted)
    set(_output "${_output}\n${_extracted}" PARENT_SCOPE)
endfunction()
extract_between("src/Deferred.cpp" "#ifdef DEVBENCH_BRIDGE_ENABLED\nnamespace" "struct DepthStates"
)
extract_between("src/Deferred.cpp" "bool Deferred::IsSceneDepthFinal()" "void Deferred::DeferredPasses()")
extract_between("src/Deferred.cpp" "void Deferred::EarlyPrepasses()" "void Deferred::PrepassPasses()")
extract_between("src/Deferred.cpp" "void Deferred::Hooks::Main_RenderWorld_Start::thunk" "void Deferred::Hooks::BSCubeMapCamera_RenderCubemap::thunk")
set(_output "${_output}\nnamespace Util {\n")
extract_between("src/Utils/D3D.cpp" "ID3D11ShaderResourceView* GetCurrentSceneDepthSRV(bool prefer16bit)" "void BindFrameBufferConstantBuffersForCS")
set(_output "${_output}\n}\n")
file(WRITE "${OUTPUT_DIRECTORY}/scene_depth_under_test.h" "${_output}")
