function(append_section source start_marker end_marker)
    string(FIND "${source}" "${start_marker}" _start)
    string(FIND "${source}" "${end_marker}" _end)
    if(_start EQUAL -1 OR _end LESS_EQUAL _start)
        message(FATAL_ERROR "Cannot extract Stabilizer API section: ${start_marker}")
    endif()
    math(EXPR _length "${_end} - ${_start}")
    string(SUBSTRING "${source}" ${_start} ${_length} _section)
    file(APPEND "${OUTPUT_FILE}" "${_section}\n")
endfunction()

file(WRITE "${OUTPUT_FILE}" "")
file(READ "${PROJECT_ROOT}/src/Features/Upscaling.cpp" _upscaling)
append_section("${_upscaling}" "VRFpsStabilizerTransitionTarget ResolveVRFpsStabilizerTransitionTarget(" "bool HasCurrentVRRenderScaleControllerTarget(")
append_section("${_upscaling}" "bool Upscaling::IsVRFpsStabilizerAPITransitionProfileAllowed(" "void Upscaling::QueueVRFpsStabilizerLoadSync(")

file(READ "${PROJECT_ROOT}/include/VRAPI/CSpluginapi.h" _api)
file(APPEND "${OUTPUT_FILE}" "namespace CSPluginAPI {\nnamespace detail {\n")
append_section("${_api}" "inline bool IsValidUpscalePreset(" "inline Upscaling::UpscaleMethod GetLegacyDLSSPreferredUpscaleMethod(")
append_section("${_api}" "inline bool ShouldBlockVRUpscalingTransitionProfileApply(" "\n\t}\n\n\tinline CSInterface001 g_interface001;")
file(APPEND "${OUTPUT_FILE}" "}\n")
append_section("${_api}" "inline void CSInterface001::SetVRUpscalingTransitionProfileForMethod(" "inline uint32_t CSInterface001::GetVRUpscalingApplyBlockReasons()")
append_section("${_api}" "inline VRUpscalingTransitionProfileDecision CSInterface001::GetVRUpscalingTransitionProfileDecision(" "}  // namespace CSPluginAPI")
file(APPEND "${OUTPUT_FILE}" "}\n")
