if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
set(_output "")
function(extract_between path start end)
    file(READ "${PROJECT_ROOT}/${path}" _source)
    string(FIND "${_source}" "${start}" _start)
    if(_start EQUAL -1)
        message(FATAL_ERROR "Ordinary save integration cannot find ${start}")
    endif()
    string(SUBSTRING "${_source}" ${_start} -1 _remaining)
    string(FIND "${_remaining}" "${end}" _end)
    if(_end EQUAL -1)
        message(FATAL_ERROR "Ordinary save integration cannot find ${end}")
    endif()
    string(SUBSTRING "${_remaining}" 0 ${_end} _extracted)
    set(_output "${_output}\n${_extracted}" PARENT_SCOPE)
endfunction()
set(_output
    "class State {\npublic:\nuint32_t frameCount = 1;\nstd::atomic_uint32_t frameCountAtomic{1};\nbool isMainMenuOpen = false;\nbool isLoadingMenuOpen = false;\nbool IsMainOrLoadingMenuOpen() const { return isMainMenuOpen || isLoadingMenuOpen; }\n"
)
extract_between("src/State.h" "static constexpr uint32_t kSaveLoadSafeModeGraceFrames" "// In-memory serialization")
extract_between("src/State.h" "bool pendingPostLoadRuntimeReset" "bool activeReflections")
set(_output "${_output}\nprivate:\n")
extract_between("src/State.h" "mutable std::mutex saveLoadSafeModeMutex" "uint64_t BeginRenderTargetResourcePublication()")
set(_output "${_output}\n};\nnamespace {\n")
extract_between("src/State.cpp" "void StoreMax(" "void ForceDisableAtBootFeature(")
set(_output "${_output}\n}\n")
extract_between("src/State.cpp" "bool State::IsSaveLoadSafeModeActive()" "void State::Reset()")
file(WRITE "${OUTPUT_DIRECTORY}/ordinary_save_state_under_test.h" "${_output}")
