if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()

file(READ "${PROJECT_ROOT}/src/Features/Upscaling.cpp" _source)
file(READ "${PROJECT_ROOT}/src/Features/Upscaling.h" _header)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")

function(extract_between source start end output)
    string(FIND "${source}" "${start}" _start)
    if(_start EQUAL -1)
        message(FATAL_ERROR "Promotion integration cannot find ${start}")
    endif()
    string(SUBSTRING "${source}" ${_start} -1 _remaining)
    string(FIND "${_remaining}" "${end}" _end)
    if(_end EQUAL -1)
        message(FATAL_ERROR "Promotion integration cannot find ${end}")
    endif()
    string(SUBSTRING "${_remaining}" 0 ${_end} _extracted)
    set(${output} "${_extracted}" PARENT_SCOPE)
endfunction()

extract_between("${_source}" "void Upscaling::ArmSubmitStageVendorResumeCooldown(" "void Upscaling::RecordSubmitStageBoundsFallback(" _promotion)
extract_between("${_source}" "VRRelatchReleasePolicy::RetryHistory Upscaling::GetOwnedReleaseRetryHistory(" "bool Upscaling::IsVRRenderScaleOwnedDrainConsumable()" _history)
extract_between("${_source}" "bool Upscaling::CanUseVRRenderScaleOwnedRelease(" "void Upscaling::ArmSubmitStageVendorResumeCooldown(" _release)
extract_between("${_source}" "ownedRelease.method = relatchUpscaleMethod;" "uint64_t expectedGuardEpoch = relatchEpoch;" _publication)
extract_between("${_header}" "struct VRRenderScaleRelatchDrainState" "VRRenderScaleRelatchDrainState vrRenderScaleRelatchDrain{};" _drain_state)
extract_between("${_header}" "struct VRRenderScaleOwnedReleaseReceipt" "\n\tuint64_t vrRenderScaleOwnedReleaseRejectedEpoch" _release_state)
string(REGEX MATCH "static constexpr size_t kVRRetiredIntermediateTextureMaxSets = [0-9]+u;" _retirement_capacity "${_header}")
if(NOT _retirement_capacity)
    message(FATAL_ERROR "Promotion integration cannot find retirement capacity")
endif()
extract_between("${_source}" "uint32_t ElapsedFrames(" "\n\t}" _elapsed)
set(_constants "")
foreach(_name kVRUpscalingTransitionApplyDelayFrames kVRSubmitStageVendorRelatchStableFrames kVRSubmitStageVendorDoorHandoffStableFrames)
    string(REGEX MATCH "constexpr uint32_t ${_name} = [0-9]+u;" _constant "${_source}")
    if(NOT _constant)
        message(FATAL_ERROR "Promotion integration cannot find ${_name}")
    endif()
    string(APPEND _constants "${_constant}\n")
endforeach()
file(WRITE "${OUTPUT_DIRECTORY}/vr_relatch_promotion_under_test.h" "${_promotion}")
file(WRITE "${OUTPUT_DIRECTORY}/vr_relatch_promotion_helpers_under_test.h" "${_constants}\n${_elapsed}\n}\n")
file(WRITE "${OUTPUT_DIRECTORY}/vr_relatch_release_state_under_test.h" "${_retirement_capacity}\n${_drain_state}\n${_release_state}")
file(WRITE "${OUTPUT_DIRECTORY}/vr_relatch_release_under_test.h" "${_history}\n${_release}")
file(WRITE "${OUTPUT_DIRECTORY}/vr_relatch_publication_under_test.h" "${_publication}")
