if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()

file(READ "${PROJECT_ROOT}/src/Features/Upscaling.cpp" _source)
file(READ "${PROJECT_ROOT}/src/Features/Upscaling.h" _header)
file(READ "${PROJECT_ROOT}/src/Features/Upscaling/FidelityFX.cpp" _fsr)
file(READ "${PROJECT_ROOT}/src/Features/Upscaling/Streamline.cpp" _dlss)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")

function(extract_between source start end output)
    string(FIND "${source}" "${start}" _start)
    if(_start EQUAL -1)
        message(FATAL_ERROR "Owned drain controller test cannot find ${start}")
    endif()
    string(SUBSTRING "${source}" ${_start} -1 _remaining)
    string(FIND "${_remaining}" "${end}" _end)
    if(_end EQUAL -1)
        message(FATAL_ERROR "Owned drain controller test cannot find ${end}")
    endif()
    string(SUBSTRING "${_remaining}" 0 ${_end} _extracted)
    set(${output} "${_extracted}" PARENT_SCOPE)
endfunction()

extract_between("${_source}" "bool Upscaling::RequiresVRRenderScaleRelatchFrameBoundary()" "bool Upscaling::ApplyPendingPerfModeRenderTargetRecreate(" _controller)
extract_between("${_header}" "struct VRRenderScaleRelatchDrainState" "VRRenderScaleRelatchDrainState vrRenderScaleRelatchDrain{};" _state)
extract_between("${_source}" "uint32_t ElapsedFrames(" "\n\t}" _elapsed)
string(REGEX MATCH "constexpr uint32_t kVRUpscalingTransitionApplyDelayFrames = [0-9]+u;" _delay "${_source}")
if(NOT _delay)
    message(FATAL_ERROR "Owned drain controller test cannot find the apply delay")
endif()
extract_between("${_source}" "thread_local bool g_vrRelatchFrameBoundaryActive" "\n\tconstexpr uint32_t kDefaultRenderScaleQualityMode" _scope)
extract_between("${_source}" "const uint64_t relatchDrainEpoch = vrRenderScaleRelatchDrain.epoch == relatchEpoch" "\n\t\tif (emitDiagLogs)" _cleanup)
extract_between("${_fsr}" "void FidelityFX::CancelFSRRelatchDrain()" "FidelityFX::LifecycleResult FidelityFX::PollFSRRelatchDrain(" _fsr_proof)
extract_between("${_dlss}" "void Streamline::CancelDLSSRelatchDrain()" "Streamline::DLSSResourceTeardownResult Streamline::PollDLSSRelatchDrain(" _dlss_proof)
extract_between("${_source}" "VRRelatchReleasePolicy::RetryHistory Upscaling::GetOwnedReleaseRetryHistory(" "bool Upscaling::CanUseVRRenderScaleOwnedRelease(" _consumable)

file(WRITE "${OUTPUT_DIRECTORY}/vr_relatch_drain_controller_under_test.h" "${_controller}")
file(WRITE "${OUTPUT_DIRECTORY}/vr_relatch_drain_state_under_test.h" "${_state}")
file(WRITE "${OUTPUT_DIRECTORY}/vr_relatch_drain_helpers_under_test.h" "${_scope}\n${_delay}\n${_elapsed}\n}\n")
file(WRITE "${OUTPUT_DIRECTORY}/vr_relatch_drain_cleanup_under_test.h" "${_cleanup}")
file(WRITE "${OUTPUT_DIRECTORY}/vr_relatch_drain_providers_under_test.h" "${_fsr_proof}\n${_dlss_proof}")
file(WRITE "${OUTPUT_DIRECTORY}/vr_relatch_drain_consumable_under_test.h" "${_consumable}")
