if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()

file(READ "${PROJECT_ROOT}/src/Features/ScreenshotFeature.cpp" _source)
file(READ "${PROJECT_ROOT}/src/Features/ScreenshotFeature.h" _header)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")

function(extract_between source start end output)
    string(FIND "${source}" "${start}" _start)
    if(_start EQUAL -1)
        message(FATAL_ERROR "Screenshot capture test cannot find ${start}")
    endif()
    string(SUBSTRING "${source}" ${_start} -1 _remaining)
    string(FIND "${_remaining}" "${end}" _end)
    if(_end EQUAL -1)
        message(FATAL_ERROR "Screenshot capture test cannot find ${end}")
    endif()
    string(SUBSTRING "${_remaining}" 0 ${_end} _extracted)
    set(${output} "${_extracted}" PARENT_SCOPE)
endfunction()

extract_between("${_header}" "enum class VRCaptureSource" "enum class VRFramedView" _source_enum)
extract_between("${_header}" "enum class OutputView" "struct OutputPlan" _view_enum)
file(WRITE "${OUTPUT_DIRECTORY}/screenshot_capture_types_under_test.h"
    "${_source_enum}\n${_view_enum}\n")

string(FIND "${_source}" "const bool geometryFallback" _geometry_fallback)
if(_geometry_fallback EQUAL -1)
    set(_selection_end "if (requiresStereoGeometry")
else()
    set(_selection_end "const bool geometryFallback")
endif()
extract_between("${_source}" "VRCaptureSource requestedSource =" "${_selection_end}" _selection)
file(WRITE "${OUTPUT_DIRECTORY}/screenshot_capture_selection_under_test.h" "${_selection}")

string(REGEX MATCH "constexpr uint32_t kCaptureTimeoutPresents = [0-9]+;" _timeout "${_source}")
if(_timeout STREQUAL "")
    message(FATAL_ERROR "Screenshot capture test cannot find the Present timeout")
endif()
extract_between("${_source}" "bool IsFramedCapture(" "const char* DescribeCaptureSource(" _classification)
extract_between("${_source}" "void ScreenshotFeature::SetEnabled(" "void ScreenshotFeature::SourceDeadlineLoop(" _set_enabled)
extract_between("${_source}" "void ScreenshotFeature::OnBeforePresent(" "void ScreenshotFeature::DrawPostCaptureIndicator(" _present)
file(WRITE "${OUTPUT_DIRECTORY}/screenshot_capture_present_under_test.h"
    "${_timeout}\n${_classification}\n${_set_enabled}\n${_present}")
