if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()
file(READ "${PROJECT_ROOT}/src/Features/Upscaling.cpp" _source)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
include("${CMAKE_CURRENT_LIST_DIR}/extract_source_region.cmake")
extract_between("${_source}" "\ttemplate <class Fn>\n\tstruct ScopeExit" "\tconstexpr float kPeripheryTAAOuterScaleMin" "depth_encode_scope_exit.h")
extract_between("${_source}" "\tstd::uintptr_t GetCOMIdentityAddress(" "\tbool IsRenderScaleQualityMode(" "depth_encode_identity.h")
extract_between("${_source}" "\tbool TryGetTexture2DDesc(" "\tbool SameTexture2DDesc(" "depth_encode_texture_desc.h")
extract_between("${_source}" "\tbool ViewReferencesResource(" "\tbool HasCompatibleCommonVendorViews(" "depth_encode_validation.h")
