if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()
file(READ "${PROJECT_ROOT}/src/Features/ScreenshotApi.cpp" _source)
file(READ "${PROJECT_ROOT}/src/Features/ScreenshotApi.h" _header)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
function(extract_worker_region source start end output)
    string(FIND "${source}" "${start}" _start)
    if(_start EQUAL -1)
        message(FATAL_ERROR "Screenshot worker test cannot find ${start}")
    endif()
    string(SUBSTRING "${source}" ${_start} -1 _remaining)
    string(FIND "${_remaining}" "${end}" _end)
    if(_end EQUAL -1)
        message(FATAL_ERROR "Screenshot worker test cannot find ${end}")
    endif()
    string(SUBSTRING "${_remaining}" 0 ${_end} _extracted)
    set(${output} "${_extracted}" PARENT_SCOPE)
endfunction()
extract_worker_region("${_header}" "struct RequestRecord" "json HandleValidatedRequest(" _types)
extract_worker_region("${_source}" "ScreenshotApi::ScreenshotApi(" "void ScreenshotApi::ManifestWorkerLoop(" _preparation)
extract_worker_region("${_source}" "void ScreenshotApi::ManifestWorkerLoop(" "ScreenshotApi::json ScreenshotApi::HandleRequest(" _manifest)
extract_worker_region("${_source}" "void ScreenshotApi::TryFinalizeSequenceLocked(" "std::optional<ScreenshotApi::DueFrame>" _publication)
extract_worker_region("${_source}" "void ScreenshotApi::MarkSequenceCancellationLocked(" "void ScreenshotApi::CancelQueuedDispatchesLocked(" _cancellation)
extract_worker_region("${_source}" "void ScreenshotApi::OnFeatureDisabled(" "std::filesystem::path ScreenshotApi::ResolveDestinationDirectory(" _shutdown)
file(WRITE "${OUTPUT_DIRECTORY}/screenshot_worker_types_under_test.h" "${_types}")
file(WRITE "${OUTPUT_DIRECTORY}/screenshot_worker_lanes_under_test.h" "${_preparation}\n${_manifest}\n${_publication}\n${_cancellation}\n${_shutdown}")
