if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()

file(READ "${PROJECT_ROOT}/src/Features/ScreenSpaceGI.cpp" _ssgi)
file(READ "${PROJECT_ROOT}/src/ProfilerDevBenchBridge.cpp" _bridge)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")

function(extract_between source start end output)
    string(FIND "${source}" "${start}" _start)
    if(_start EQUAL -1)
        message(FATAL_ERROR "OCU integration test cannot find ${start}")
    endif()
    string(SUBSTRING "${source}" ${_start} -1 _remaining)
    string(FIND "${_remaining}" "${end}" _end)
    if(_end EQUAL -1)
        message(FATAL_ERROR "OCU integration test cannot find ${end}")
    endif()
    string(SUBSTRING "${_remaining}" 0 ${_end} _extracted)
    file(WRITE "${OUTPUT_DIRECTORY}/${output}" "${_extracted}")
endfunction()

extract_between("${_ssgi}" "bool ScreenSpaceGI::CompileComputeShaders(" "bool ScreenSpaceGI::ShadersOK()" "ocu_shader_batch_under_test.h")
extract_between("${_ssgi}" "void ScreenSpaceGI::SetOCUEffectFoveationEnabled(" "void ScreenSpaceGI::DrawOCUEffectFoveationSettings()" "ocu_setting_under_test.h")
extract_between("${_bridge}" "json BuildOCUEffectFoveationResult(" "json BuildProfilerResult(" "ocu_devbench_under_test.h")
