if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()
file(READ "${PROJECT_ROOT}/src/Features/VR/InSceneOverlay.cpp" _source)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")
function(extract_between start end output)
    string(FIND "${_source}" "${start}" _start)
    if(_start EQUAL -1)
        message(FATAL_ERROR "Native boundary integration cannot find ${start}")
    endif()
    string(SUBSTRING "${_source}" ${_start} -1 _remaining)
    string(FIND "${_remaining}" "${end}" _end)
    if(_end EQUAL -1)
        message(FATAL_ERROR "Native boundary integration cannot find ${end}")
    endif()
    string(SUBSTRING "${_remaining}" 0 ${_end} _extracted)
    set(${output} "${_extracted}" PARENT_SCOPE)
endfunction()
extract_between("struct BSOpenVR_Submit" "struct IVRCompositor_Submit" _native)
extract_between("const auto completedPairToken = g_vrSubmitPairBoundaryState.token;" "uint64_t compositorCycleState =" _eye_completion)
file(WRITE "${OUTPUT_DIRECTORY}/vr_relatch_native_boundary_under_test.h" "${_native}")
file(WRITE "${OUTPUT_DIRECTORY}/vr_relatch_native_eye_completion_under_test.h" "${_eye_completion}")
