if(NOT DEFINED PROJECT_ROOT OR NOT DEFINED OUTPUT_DIRECTORY)
    message(FATAL_ERROR "PROJECT_ROOT and OUTPUT_DIRECTORY are required")
endif()

file(READ "${PROJECT_ROOT}/src/Buffer.h" _buffer)
file(READ "${PROJECT_ROOT}/src/Features/Upscaling/DX12SwapChain.cpp" _interop)
file(MAKE_DIRECTORY "${OUTPUT_DIRECTORY}")

function(extract_between source start end output)
    string(FIND "${source}" "${start}" _start)
    if(_start EQUAL -1)
        message(FATAL_ERROR "Shared guide test cannot find ${start}")
    endif()
    string(SUBSTRING "${source}" ${_start} -1 _remaining)
    string(FIND "${_remaining}" "${end}" _end)
    if(_end EQUAL -1)
        message(FATAL_ERROR "Shared guide test cannot find ${end}")
    endif()
    string(SUBSTRING "${_remaining}" 0 ${_end} _extracted)
    set(${output} "${_extracted}" PARENT_SCOPE)
endfunction()

extract_between("${_buffer}" "HANDLE GetOrCreateSharedHandle()" "void CreateSRV(" _handle)
extract_between("${_interop}" "WrappedResource::WrappedResource(ID3D11Texture2D*" "WrappedResource::WrappedResource(D3D11_TEXTURE2D_DESC" _import)
file(WRITE "${OUTPUT_DIRECTORY}/shared_guide_handle_under_test.h" "${_handle}")
file(WRITE "${OUTPUT_DIRECTORY}/shared_guide_import_under_test.h" "${_import}")
